apiVersion: v1
kind: Service
matedata:
  name: todoapp-clusterIp
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
